name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Install Scala CLI
      run: |
        curl -sSLf https://scala-cli.virtuslab.org/get | sh
        echo "$HOME/.scala-cli/bin" >> $GITHUB_PATH
        # Make scala-cli available in this step
        export PATH="$HOME/.scala-cli/bin:$PATH"
    - name: Run tests
      run: |
        # Ensure scala-cli is in the PATH
        export PATH="$HOME/.scala-cli/bin:$PATH" 
        scala-cli test .
    - name: Compile
      run: |
        export PATH="$HOME/.scala-cli/bin:$PATH"
        scala-cli compile .
